repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.4
    hooks:
      - id: flake8
        args: [ '--config=setup.cfg' ]
        additional_dependencies:
          - flake8-bugbear  # finding likely bugs and design problems
          - flake8-builtins  # check for python builtins being used as variables or parameters
          - pep8-naming  # check PEP-8 naming conventions, plugin for flake8
          - flake8-commas  # flake8 lint for trailing commas
